export const Const = {
  RENDER_REQUEST: "RENDER_REQUEST",
  RENDER_SUCCESS: "RENDER_SUCCESS",
  RENDER_ERROR: "RENDER_ERROR",

  CLICK_REQUEST: "CLICK_REQUEST",
  CLICK_SUCCESS: "CLICK_SUCCESS",
  CLICK_ERROR: "CLICK_ERROR",

  REROLL_REQUEST: "REROLL_REQUEST",
  REROLL_SUCCESS: "REROLL_SUCCESS",
  REROLL_ERROR: "REROLL_ERROR",
}